### ISSUE TITLE
Cross-compile example

### ISSUE THREAD

**Issue by xoac** [berkowski/tokio-serial#13]
Hi,

I wanted to cross-compile this crate for arm:
I used `docker` and this commends in root crate directory:
```
docker run --rm -it -v "$(pwd)"/target/armv7-unknown-linux-musleabihf/musl-builder/cargo-cache:/root/.cargo/registry -v "$(pwd)":/home/rust/src messense/rust-musl-cross:armv7-musleabihf cargo test
```
Output:
```
 Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading mio v0.6.14                                                        
 Downloading bytes v0.4.8                                                       
 Downloading tokio v0.1.6                                                       
 Downloading futures v0.1.21                                                    
 Downloading mio-serial v0.8.0                                                  
 Downloading tokio-reactor v0.1.1                                               
 Downloading tokio-io v0.1.6                                                    
 Downloading net2 v0.2.32                                                       
 Downloading iovec v0.1.2                                                       
 Downloading slab v0.4.0                                                        
 Downloading log v0.4.1                                                         
 Downloading libc v0.2.41                                                       
 Downloading lazycell v0.6.0                                                    
 Downloading cfg-if v0.1.3                                                      
 Downloading byteorder v1.2.3                                                   
 Downloading tokio-timer v0.2.3                                                 
 Downloading tokio-fs v0.1.0                                                    
 Downloading tokio-threadpool v0.1.3                                            
 Downloading tokio-executor v0.1.2                                              
 Downloading tokio-udp v0.1.0                                                   
 Downloading tokio-tcp v0.1.0                                                   
 Downloading rand v0.4.2                                                        
 Downloading num_cpus v1.8.0                                                    
 Downloading crossbeam-deque v0.3.1                                             
 Downloading crossbeam-utils v0.3.2                                             
 Downloading crossbeam-epoch v0.4.1                                             
 Downloading arrayvec v0.4.7                                                    
 Downloading memoffset v0.2.1                                                   
 Downloading scopeguard v0.3.3                                                  
 Downloading lazy_static v1.0.0                                                 
 Downloading nodrop v0.1.12                                                     
 Downloading nix v0.10.0                                                        
 Downloading serialport v2.3.0                                                  
 Downloading void v1.0.2                                                        
 Downloading bitflags v1.0.3                                                    
 Downloading bitflags v0.9.1                                                    
 Downloading libudev v0.2.0                                                     
 Downloading libudev-sys v0.1.4                                                 
 Downloading pkg-config v0.3.11                                                 
   Compiling pkg-config v0.3.11                                                 
   Compiling libc v0.2.41
   Compiling nodrop v0.1.12
   Compiling cfg-if v0.1.3
   Compiling scopeguard v0.3.3
   Compiling lazy_static v1.0.0
   Compiling nix v0.10.0
   Compiling byteorder v1.2.3
   Compiling memoffset v0.2.1
   Compiling bitflags v1.0.3
   Compiling lazycell v0.6.0
   Compiling void v1.0.2
   Compiling slab v0.4.0
   Compiling futures v0.1.21
   Compiling bitflags v0.9.1
   Compiling arrayvec v0.4.7
   Compiling crossbeam-utils v0.3.2
   Compiling log v0.4.1
   Compiling iovec v0.1.2
   Compiling net2 v0.2.32
   Compiling num_cpus v1.8.0
   Compiling rand v0.4.2
   Compiling libudev-sys v0.1.4
   Compiling crossbeam-epoch v0.4.1
   Compiling bytes v0.4.8
   Compiling mio v0.6.14
error: failed to run custom build command for `libudev-sys v0.1.4`
process didn't exit successfully: `/home/rust/src/target/debug/build/libudev-sys-37b2fd985452dc24/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Cross compilation detected. Use PKG_CONFIG_ALLOW_CROSS=1 to override"', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```
--------------------

With suggestion form compilator:
```
docker run --rm -it -e "PKG_CONFIG_ALLOW_CROSS=1" -v "$(pwd)"/target/armv7-unknown-linux-musleabihf/musl-builder/cargo-cache:/root/.cargo/registry -v "$(pwd)":/home/rust/src messense/rust-musl-cross:armv7-musleabihf cargo test
```
Output
```
   Compiling tokio-executor v0.1.2
   Compiling libudev-sys v0.1.4
   Compiling nix v0.10.0
   Compiling tokio-io v0.1.6
error: failed to run custom build command for `libudev-sys v0.1.4`
process didn't exit successfully: `/home/rust/src/target/debug/build/libudev-sys-37b2fd985452dc24/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"`: No such file or directory (os error 2)"', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

Has anyone successfully cross-compiled this crate?

**Comment by xoac** [comment]
Ok. I go some steps forward. 
Let's see this step by step:
1) Go to interactive console in `tokio-serial` source dir.
```
docker run --rm -it -v "$(pwd)"/target/armv7-unknown-linux-musleabihf/musl-builder/cargo-cache:/root/.cargo/registry -v "$(pwd)":/home/rust/src messense/rust-musl-cross:armv7-musleabihf
```
2) Add armhf architecture
```
# dpkg --add-architecture armhf
```
3) Modify source-list (end of file)
```
root@69868e92a02b:/home/rust/src# cat /etc/apt/sources.list
# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://archive.ubuntu.com/ubuntu/ xenial main restricted
# deb-src http://archive.ubuntu.com/ubuntu/ xenial main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://archive.ubuntu.com/ubuntu/ xenial-updates main restricted
# deb-src http://archive.ubuntu.com/ubuntu/ xenial-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://archive.ubuntu.com/ubuntu/ xenial universe
deb-src http://archive.ubuntu.com/ubuntu/ xenial universe
deb http://archive.ubuntu.com/ubuntu/ xenial-updates universe
deb-src http://archive.ubuntu.com/ubuntu/ xenial-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team, and may not be under a free licence. Please satisfy yourself as to
## your rights to use the software. Also, please note that software in
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://archive.ubuntu.com/ubuntu/ xenial multiverse
# deb-src http://archive.ubuntu.com/ubuntu/ xenial multiverse
deb http://archive.ubuntu.com/ubuntu/ xenial-updates multiverse
# deb-src http://archive.ubuntu.com/ubuntu/ xenial-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse
# deb-src http://archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu xenial partner
# deb-src http://archive.canonical.com/ubuntu xenial partner

deb http://security.ubuntu.com/ubuntu/ xenial-security main restricted
# deb-src http://security.ubuntu.com/ubuntu/ xenial-security main restricted
deb http://security.ubuntu.com/ubuntu/ xenial-security universe
deb-src http://security.ubuntu.com/ubuntu/ xenial-security universe
deb http://security.ubuntu.com/ubuntu/ xenial-security multiverse
# deb-src http://security.ubuntu.com/ubuntu/ xenial-security multiverse
# #########################
# source urls for armhf
deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ xenial main 
deb-src [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ xenial main 
deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ xenial-updates main
deb-src [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ xenial-updates main 
deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ xenial-security main 
deb-src [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ xenial-security main
 # end armhf section
```
4) Install pkg-config
```
# apt-get update &&  apt-get install pkg-config
```
5) Install lib for armhf. (I wanted link my lib statically if it is possible - so here is 1 problem but let's say I want just successfully compile)
```
# apt-get install libudev-dev:armhf
```
6) let's try build example
```
# cargo build --examples
```

And output:
```
root@69868e92a02b:/home/rust/src# cargo build --examples
   Compiling tokio-serial v0.8.0 (file:///home/rust/src)
error: linking with `armv7-unknown-linux-musleabihf-gcc` failed: exit code: 1
  |
  = note: "armv7-unknown-linux-musleabihf-gcc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-nostdlib" "-Wl,--eh-frame-hdr" "-Wl,-(" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-musleabihf/lib/crt1.o" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-musleabihf/lib/crti.o" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-musleabihf/lib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.11ghxnayh8xpl17k.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.138pesuvab4dy035.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.13tprap6axy2fph1.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.15kq92zzbmxot4k9.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.16u6js6g0l3k1ic6.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.17xo5jnw571b1rnw.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.195mewh71jd32du7.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.1ckp3bwk0jmrbky4.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.1e698527iprj2v8f.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.1eldthk14htjpe8q.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.1im38lueib99jsk0.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.1o80id2q0u32107p.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.1rv8n017ha9022uu.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.1vut2eft6nlujjxr.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.1y16o1qfye96o7m0.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.1zeawhkbeobww1zn.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.1zlxkqmuhdjcaqn9.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.23tqyymcb18u96mb.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.2cxgixxswi5wkeip.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.2dh9yuzgscovothb.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.2hqjw4a4bn2aa68y.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.2jqywn86b2gsqohu.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.2lyh15q6cjwzy18c.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.2oiwwqohid6mabhc.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.2qhkzqx5zqexj20y.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.2wzbhs8bqvpehnc7.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.2yf0izvq9wmxs9a5.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.2z4vhc57novzw9tv.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.3171x0bwu82dptu7.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.33uanrnvs5dp6udw.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.365v8i4tldudjl4f.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.3ayaeypdcro9d6yk.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.3ce0i2u5ozf066mh.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.3cx7oljifvb206q7.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.3f6klegmryfg2ey3.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.3fv3oe9p41gdwj5k.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.3g94tobrpgum5dk6.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.3ik0x0hz6l66cx38.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.3leyp4wxhlcx35ib.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.3oqznv5oym7l3m4e.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.3p7mbnaeakts9q7d.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.3rf6apwr5rc5zixx.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.3rngp6bm2u2q5z0y.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.3vck0z67htzlxjio.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.3vz1yfl7wp1xiunk.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.3y4wailk3b6grf6c.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.40ambqzc7mt87tgc.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.436dotimmrgzkwfa.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.43eo90tsl80o84z8.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.45nf4z58qqykpcpi.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.45pc7c65foh9i35f.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.48721dc4k5qxei0u.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.48sm2phqfqdqp42l.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.49a7n47po4ttqjl7.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.49lx1q7cxvpykyv0.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.49qmpuk8w1opmi5q.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.4b8ptp1vn215jmoe.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.4ezmh1vbs95c5ack.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.4xq48u46a1pwiqn7.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.4ybye971cqflgun6.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.4yh8x2b62dcih00t.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.4ypvbwho0bu5tnww.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.4zvzya2emnpje6ln.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.51s1w397y42gpez1.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.572bgozz9kcwe4zq.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.57k06xfugllsc526.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.58obdilhk3rtglcy.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.5f5jc0oo6c9dh2oo.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.7p53qlves2rwxx0.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.8n5lnckn5hfrxm0.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.8xzrsc1ux72v29j.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.98g0d9x8aw3akpe.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.9elsx31vb4it187.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.c6lbtaiefvx3wya.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.d6p2df93qm1h3gm.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.e19kx9t7xhzajfl.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.erk1i9fwougo95j.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.gon14xphovlcp6p.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.i7m1rpix4ruptp7.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.j88x78foflefssm.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.jkawlvpumsc6s4c.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.kszai26leddh1lg.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.mb501chi8fnqgmm.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.pqmjx25qpxkduz7.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.qpucyjripxdv9xh.rcgu.o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.yx3ia2hr9pm1qoy.rcgu.o" "-o" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/examples/serial_println-b63392149eb05d20.crate.allocator.rcgu.o" "-Wl,--gc-sections" "-no-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs" "-L" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps" "-L" "/home/rust/src/target/debug/deps" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-musleabihf/lib" "-Wl,-Bstatic" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-musleabihf/lib/liballoc_jemalloc-f68d8e8245e507c6.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libtokio_serial-267b857f4a8e2539.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libmio_serial-7ab9438e1f56a6c2.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libserialport-b1879f39129d9792.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libbitflags-a287bb825bb54d4f.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libnix-bf56b91a1fca1bcf.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libvoid-c3207025e914684a.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libbitflags-d18cb012f8fef78f.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/liblibudev-26b5f3a51b49dd29.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/liblibudev_sys-f6bf3368f2693f6d.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libtokio-ab9ce1d3007097f7.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libtokio_udp-2b3089ae1dbe21c6.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libtokio_tcp-001b6b81f85fa040.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libtokio_timer-7c6f0f58c29c99b2.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libtokio_reactor-b9dae11afb9f0b89.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libtokio_fs-c6f994ef6bf5db6a.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libtokio_threadpool-96c7f86577d45c8e.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/librand-5f180f3e2ebb8495.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libnum_cpus-a346406cbe9d9bd1.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libcrossbeam_deque-63037901456e94a2.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libcrossbeam_epoch-9e2e55aad4687481.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libscopeguard-e608ef0ffdcaad27.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libmemoffset-149f6ed9f605cd7b.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/liblazy_static-7c819e3daef53e0c.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libcrossbeam_utils-6451544d5a00087d.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libarrayvec-bc3c520652462091.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libnodrop-be36956243b6d79f.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libtokio_executor-61230ec28dd0a7ad.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libtokio_io-5c8a4e747adf57a8.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libmio-0d077f612b9390e5.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/liblog-9631fe6d33431cb3.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libslab-4cf90430dd41c37b.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libnet2-1ccae07ae1cd8146.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libcfg_if-74c642e6707421e7.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/liblazycell-f8f7e8d9a0de6c32.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libfutures-5b956a4db5559ac0.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libbytes-059e7c7778130e24.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libiovec-de33f2349d037c05.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/liblibc-743abe886a843383.rlib" "/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libbyteorder-884110d3e2495e9d.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-musleabihf/lib/libstd-8d847bbe97fc9dc5.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-musleabihf/lib/libpanic_unwind-008c42aad548e7dd.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-musleabihf/lib/libunwind-0fe53371ec419e32.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-musleabihf/lib/liballoc_system-9dec1cbd51097ce1.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-musleabihf/lib/liblibc-6a4fb915dd86d140.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-musleabihf/lib/liballoc-7ebba6af2d3cc324.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-musleabihf/lib/libstd_unicode-7a26f8b3cf380464.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-musleabihf/lib/libcore-b0c2d164a9741309.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-musleabihf/lib/libcompiler_builtins-66d072e25a9acee3.rlib" "-Wl,-Bdynamic" "-l" "udev" "-static" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-musleabihf/lib/crtn.o" "-Wl,-)"
  = note: /usr/local/musl/bin/../lib/gcc/armv7-unknown-linux-musleabihf/7.2.0/../../../../armv7-unknown-linux-musleabihf/bin/ld: cannot find -ludev
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `tokio-serial`.

To learn more, run the command again with --verbose.
```

**Comment by berkowski** [comment]
Hi xaoc,

This might be a dumb question; but did installing `libudev-dev` bring in `libudev` as well?  

I haven't tried cross compiling anything in rust myself yet and I've relied on [rust-cross](https://github.com/japaric/rust-cross) for the CI tests on travis.  I don't see a `--target=` flag in your `cargo build` statements though.  

What happens if you try `cargo build --target=armv7-unknown-linux-musleabihf --examples`?

**Comment by xoac** [comment]
@berkowski The problem is much more complicated. Generally I don't need list all possible ports and devices so I don't need `libudev` what is more I think there is nobody who wants to use `udev` stuff with `musl`. So the problem start [here](https://gitlab.com/susurrus/serialport-rs/issues/42) And I am near to resolve this issue. I think `libudev` should be as features.

Are you from Poland?

**Comment by ndusart** [comment]
@xoac I agree that we should be able to choose to use libudev or not with a feature but it is not set in this crate but the upstream serialport-rs (https://gitlab.com/susurrus/serialport-rs).

libudev is only used for the function `available_ports` so I think it is ok to opt-out from it.

You should open an issue in upstream.

**Comment by berkowski** [comment]
@xoac 

Ah, OK.  I'll follow that issue and the associated PR, making the changes to mio-serial and tokio-serial as needed.

Not from Poland directly; part of the family tree has roots in the area :)

**Comment by xoac** [comment]
@berkowski @ndusart libudev dependencies start in serialport-rs i made a PR to support musl.

**Comment by xoac** [comment]
So this get stuck https://gitlab.com/susurrus/serialport-rs/merge_requests/44 
any plans to support serialport-rs 3.0 when ready?

**Comment by berkowski** [comment]
@xoac, yes.  I'd like to keep both `mio-serial` and `tokio-serial` tracking `serialport-rs`.

**Comment by xoac** [comment]
@berkowski serialport-rs v3.0.0 is ready https://gitlab.com/susurrus/serialport-rs

I have also forked your project and support cross-compile here https://github.com/xoac/tokio-serial/tree/serialport_rs_2_3_1 with PR from here https://gitlab.com/susurrus/serialport-rs/merge_requests/48

**Comment by berkowski** [comment]
Thanks for the notice!

I just published mio-serial/tokio-serial based on serialport-rs 3.0.  Have a try and let me know how it goes.

**Comment by berkowski** [comment]
Great!
