### ISSUE TITLE
there is no reactor running, must be called from the context of a Tokio 1.x runtime

### ISSUE THREAD

**Issue by brandonros** [berkowski/tokio-serial#51]
```rust
        let runtime = tokio::runtime::Builder::new_multi_thread()
            .enable_all()
            .build()
            .unwrap();

        // Open serial port
        let serial = tokio_serial::new(port, baudrate)
            .open_native_async()
            .map_err(|_| j2534::Error::DeviceNotConnected)?;
```

**Comment by brandonros** [comment]
```
Open /dev/cu.usbmodem11201
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /Users/brandonros/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/context.rs:29:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::panic_display
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/option.rs:1817:5
   5: core::option::Option<T>::expect
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/option.rs:692:21
   6: tokio::runtime::context::io_handle::{{closure}}
             at /Users/brandonros/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/context.rs:29:13
   7: std::thread::local::LocalKey<T>::try_with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:412:16
   8: tokio::runtime::context::io_handle
             at /Users/brandonros/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/context.rs:27:15
   9: tokio::io::driver::Handle::current
             at /Users/brandonros/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/io/driver/mod.rs:263:13
  10: tokio::io::async_fd::AsyncFd<T>::with_interest
             at /Users/brandonros/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/io/async_fd.rs:190:51
  11: tokio::io::async_fd::AsyncFd<T>::new
             at /Users/brandonros/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/io/async_fd.rs:180:9
  12: tokio_serial::SerialStream::open
             at /Users/brandonros/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-serial-5.4.3/src/lib.rs:78:24
  13: <serialport::SerialPortBuilder as tokio_serial::SerialPortBuilderExt>::open_native_async
             at /Users/brandonros/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-serial-5.4.3/src/lib.rs:528:9
  14: driver::protocol::Stream::open
             at /Users/brandonros/Desktop/stm_j2534/driver/src/protocol.rs:165:22
  15: driver::passthru::Device::open
             at /Users/brandonros/Desktop/stm_j2534/driver/src/passthru.rs:29:21
  16: PassThruOpen
             at /Users/brandonros/Desktop/stm_j2534/driver/src/lib.rs:38:24
  17: diag_test::main
             at ./src/main.rs:49:26
  18: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Brandons-MacBook-Air:diag_test brandonros 2022-04-11 12:25:10 $ 

```

**Comment by brandonros** [comment]
```
 let runtime = tokio::runtime::Builder::new_multi_thread()
            .enable_all()
            .build()
            .unwrap();
        let _guard = runtime.enter();
        // Open serial port
        let serial = tokio_serial::new(port, baudrate)
            .open_native_async()
            .map_err(|_| j2534::Error::DeviceNotConnected)?;
```

 Needed to enter runtime.
